title: "Yung-Shin (Martin) Chien test:2"
email: chien.yun@northeastern.edu
description: >- 
  This is my portfolio website!
baseurl: "/" 
url: "/" 
twitter_username: 
github_username: mchall92

sass:
  sass_dir: _sass

icon: /assets/img/profile.png